### Register new customer
POST http://localhost:9000/store/customers
Content-Type: application/json

{
    "first_name": "Alice",
    "last_name": "Reynolds",
    "email": "alice@example.com",
    "password": "supersecret"
}

### List product
GET http://localhost:9000/store/products

### List product by sale channel
GET http://localhost:9000/store/products?expand=variants,images&sales_channel_id[]=sc_01HGM244VHHQMD8EKP8DBDWSH7

### Get product
GET http://localhost:9000/store/products/prod_01HGHNMJS5RHX3NG76MHQXBQNH
 
 
### search variants
GET http://localhost:9000/store/variants

### admin token
POST http://localhost:9000/admin/auth/token
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Hello123"
}
 
### currency
GET http://localhost:9000/admin/currencies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY

### add Thai Baht currency code
POST http://localhost:9000/admin/store/currencies/thb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY

### list region 
GET http://localhost:9000/admin/regions/reg_01HGWZJEB9VEBARZBX936X8JF2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY
Content-Type: application/json

### add region Thailand
POST http://localhost:9000/admin/regions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY
Content-Type: application/json

{
    "name": "Thailand",
    "currency_code": "thb",
    "tax_rate": 0,
    "payment_providers": [
      "manual"
    ],
    "fulfillment_providers": [
      "manual"
    ],
    "countries": [
      "TH"
    ]
}

### list regoin

GET http://localhost:9000/admin/regions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY
Content-Type: application/json

 
### list sale channel

GET http://localhost:9000/admin/sales-channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNyXzAxSEdXWVg5RDEzRFdTS1FaUDRSODI4SDNQIiwiZG9tYWluIjoiYWRtaW4iLCJpYXQiOjE3MDE3Nzk2MTEsImV4cCI6MTcwMTg2NjAxMX0.IZDF_Qkv-I6uHLWedbUcxn3SujxFHEzD1Upa6SId8gY
Content-Type: application/json

 