version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:test
    ports:
      - "7001:7001"
      - "9000:9000"
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
