version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "7001:7001"
      - "9000:9000"
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  swagger-admin:
    build:
      context: ./swagger
      dockerfile: Dockerfile_admin
    image: swagger-admin:latest
    ports:
      - "4001:4001"
    container_name: swagger-admin
    depends_on:
      - backend

  swagger-store:
    build:
      context: ./swagger
      dockerfile: Dockerfile_store
    image: swagger-store:latest
    ports:
      - "4002:4002"
    container_name: swagger-store
    depends_on:
      - backend
